var React = require('react');
var StandingsData = require('../../public/data/leagueStandings.json');

var Standings = React.createClass({
  getInitialState: function() {
    var teams =
    [ {
      "awayLosses" : 4,
      "awayTies" : 0,
      "awayWins" : 0,
      "calendarYear" : 2019,
      "capAvailable" : 12790000,
      "capRoom" : 174270000,
      "capSpent" : 161480000,
      "confLosses" : 6,
      "confTies" : 0,
      "confWins" : 0,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2482,
      "defPassYdsRank" : 32,
      "defRushYds" : 939,
      "defRushYdsRank" : 29,
      "defTotalYds" : 3421,
      "defTotalYdsRank" : 32,
      "divLosses" : 4,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761153,
      "divisionName" : "AFC North",
      "homeLosses" : 4,
      "homeTies" : 0,
      "homeWins" : 0,
      "netPts" : -160,
      "offPassYds" : 1790,
      "offPassYdsRank" : 21,
      "offRushYds" : 783,
      "offRushYdsRank" : 17,
      "offTotalYds" : 2573,
      "offTotalYdsRank" : 20,
      "playoffStatus" : 0,
      "prevRank" : 27,
      "ptsAgainst" : 36,
      "ptsAgainstRank" : 30,
      "ptsFor" : 16,
      "ptsForRank" : 31,
      "rank" : 31,
      "seasonIndex" : 3,
      "seed" : 15,
      "stageIndex" : 1,
      "tODiff" : -5,
      "teamId" : 757727261,
      "teamName" : "Ravens",
      "teamOvr" : 79,
      "totalLosses" : 8,
      "totalTies" : 0,
      "totalWins" : 0,
      "weekIndex" : 8,
      "winLossStreak" : 248,
      "winPct" : 0
    }, {
      "awayLosses" : 0,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 1040000,
      "capRoom" : 174270000,
      "capSpent" : 173230000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 6,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2221,
      "defPassYdsRank" : 30,
      "defRushYds" : 809,
      "defRushYdsRank" : 19,
      "defTotalYds" : 3030,
      "defTotalYdsRank" : 29,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 4,
      "divisionId" : 755761153,
      "divisionName" : "AFC North",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 3,
      "netPts" : 49,
      "offPassYds" : 2452,
      "offPassYdsRank" : 1,
      "offRushYds" : 996,
      "offRushYdsRank" : 4,
      "offTotalYds" : 3448,
      "offTotalYdsRank" : 1,
      "playoffStatus" : 1,
      "prevRank" : 15,
      "ptsAgainst" : 24,
      "ptsAgainstRank" : 17,
      "ptsFor" : 30,
      "ptsForRank" : 7,
      "rank" : 3,
      "seasonIndex" : 3,
      "seed" : 2,
      "stageIndex" : 1,
      "tODiff" : 5,
      "teamId" : 757727265,
      "teamName" : "Steelers",
      "teamOvr" : 83,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.75
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 9840000,
      "capRoom" : 174270000,
      "capSpent" : 164430000,
      "confLosses" : 1,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2124,
      "defPassYdsRank" : 26,
      "defRushYds" : 605,
      "defRushYdsRank" : 2,
      "defTotalYds" : 2729,
      "defTotalYdsRank" : 21,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761153,
      "divisionName" : "AFC North",
      "homeLosses" : 3,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 10,
      "offPassYds" : 1701,
      "offPassYdsRank" : 22,
      "offRushYds" : 1084,
      "offRushYdsRank" : 2,
      "offTotalYds" : 2785,
      "offTotalYdsRank" : 12,
      "playoffStatus" : 0,
      "prevRank" : 14,
      "ptsAgainst" : 28,
      "ptsAgainstRank" : 28,
      "ptsFor" : 29,
      "ptsForRank" : 8,
      "rank" : 22,
      "seasonIndex" : 3,
      "seed" : 12,
      "stageIndex" : 1,
      "tODiff" : 4,
      "teamId" : 757727235,
      "teamName" : "Bengals",
      "teamOvr" : 85,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 252,
      "winPct" : 0.429
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 11970000,
      "capRoom" : 174270000,
      "capSpent" : 162300000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1648,
      "defPassYdsRank" : 9,
      "defRushYds" : 817,
      "defRushYdsRank" : 21,
      "defTotalYds" : 2465,
      "defTotalYdsRank" : 11,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761153,
      "divisionName" : "AFC North",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 29,
      "offPassYds" : 1813,
      "offPassYdsRank" : 19,
      "offRushYds" : 756,
      "offRushYdsRank" : 21,
      "offTotalYds" : 2569,
      "offTotalYdsRank" : 21,
      "playoffStatus" : 1,
      "prevRank" : 11,
      "ptsAgainst" : 20,
      "ptsAgainstRank" : 6,
      "ptsFor" : 24,
      "ptsForRank" : 17,
      "rank" : 13,
      "seasonIndex" : 3,
      "seed" : 5,
      "stageIndex" : 1,
      "tODiff" : 4,
      "teamId" : 757727238,
      "teamName" : "Browns",
      "teamOvr" : 77,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 2,
      "winPct" : 0.571
    }, {
      "awayLosses" : 0,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 13400000,
      "capRoom" : 174270000,
      "capSpent" : 160870000,
      "confLosses" : 1,
      "confTies" : 0,
      "confWins" : 5,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1596,
      "defPassYdsRank" : 2,
      "defRushYds" : 637,
      "defRushYdsRank" : 3,
      "defTotalYds" : 2233,
      "defTotalYdsRank" : 1,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 4,
      "divisionId" : 755761154,
      "divisionName" : "AFC South",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 4,
      "netPts" : 105,
      "offPassYds" : 2136,
      "offPassYdsRank" : 8,
      "offRushYds" : 752,
      "offRushYdsRank" : 22,
      "offTotalYds" : 2888,
      "offTotalYdsRank" : 8,
      "playoffStatus" : 1,
      "prevRank" : 9,
      "ptsAgainst" : 16,
      "ptsAgainstRank" : 1,
      "ptsFor" : 31,
      "ptsForRank" : 4,
      "rank" : 2,
      "seasonIndex" : 3,
      "seed" : 1,
      "stageIndex" : 1,
      "tODiff" : 6,
      "teamId" : 757727251,
      "teamName" : "Jaguars",
      "teamOvr" : 86,
      "totalLosses" : 1,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 2,
      "winPct" : 0.857
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 11980000,
      "capRoom" : 174270000,
      "capSpent" : 162290000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2183,
      "defPassYdsRank" : 28,
      "defRushYds" : 676,
      "defRushYdsRank" : 4,
      "defTotalYds" : 2859,
      "defTotalYdsRank" : 24,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 4,
      "divisionId" : 755761154,
      "divisionName" : "AFC South",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 6,
      "offPassYds" : 1900,
      "offPassYdsRank" : 16,
      "offRushYds" : 1165,
      "offRushYdsRank" : 1,
      "offTotalYds" : 3065,
      "offTotalYdsRank" : 3,
      "playoffStatus" : 0,
      "prevRank" : 4,
      "ptsAgainst" : 24,
      "ptsAgainstRank" : 16,
      "ptsFor" : 24,
      "ptsForRank" : 18,
      "rank" : 17,
      "seasonIndex" : 3,
      "seed" : 9,
      "stageIndex" : 1,
      "tODiff" : 3,
      "teamId" : 757727267,
      "teamName" : "Titans",
      "teamOvr" : 82,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.5
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 7150000,
      "capRoom" : 174270000,
      "capSpent" : 167120000,
      "confLosses" : 4,
      "confTies" : 0,
      "confWins" : 1,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2013,
      "defPassYdsRank" : 24,
      "defRushYds" : 886,
      "defRushYdsRank" : 27,
      "defTotalYds" : 2899,
      "defTotalYdsRank" : 26,
      "divLosses" : 4,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761154,
      "divisionName" : "AFC South",
      "homeLosses" : 3,
      "homeTies" : 0,
      "homeWins" : 0,
      "netPts" : -36,
      "offPassYds" : 1438,
      "offPassYdsRank" : 29,
      "offRushYds" : 746,
      "offRushYdsRank" : 23,
      "offTotalYds" : 2184,
      "offTotalYdsRank" : 31,
      "playoffStatus" : 0,
      "prevRank" : 10,
      "ptsAgainst" : 27,
      "ptsAgainstRank" : 25,
      "ptsFor" : 22,
      "ptsForRank" : 21,
      "rank" : 28,
      "seasonIndex" : 3,
      "seed" : 14,
      "stageIndex" : 1,
      "tODiff" : -4,
      "teamId" : 757727266,
      "teamName" : "Texans",
      "teamOvr" : 82,
      "totalLosses" : 5,
      "totalTies" : 0,
      "totalWins" : 2,
      "weekIndex" : 8,
      "winLossStreak" : 254,
      "winPct" : 0.286
    }, {
      "awayLosses" : 4,
      "awayTies" : 0,
      "awayWins" : 0,
      "calendarYear" : 2019,
      "capAvailable" : 4294517296,
      "capRoom" : 174270000,
      "capSpent" : 174720000,
      "confLosses" : 5,
      "confTies" : 0,
      "confWins" : 0,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1912,
      "defPassYdsRank" : 21,
      "defRushYds" : 1105,
      "defRushYdsRank" : 32,
      "defTotalYds" : 3017,
      "defTotalYdsRank" : 28,
      "divLosses" : 3,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761154,
      "divisionName" : "AFC South",
      "homeLosses" : 3,
      "homeTies" : 0,
      "homeWins" : 0,
      "netPts" : -114,
      "offPassYds" : 1855,
      "offPassYdsRank" : 17,
      "offRushYds" : 466,
      "offRushYdsRank" : 30,
      "offTotalYds" : 2321,
      "offTotalYdsRank" : 26,
      "playoffStatus" : 0,
      "prevRank" : 32,
      "ptsAgainst" : 38,
      "ptsAgainstRank" : 32,
      "ptsFor" : 21,
      "ptsForRank" : 22,
      "rank" : 32,
      "seasonIndex" : 3,
      "seed" : 16,
      "stageIndex" : 1,
      "tODiff" : 2,
      "teamId" : 757727243,
      "teamName" : "Colts",
      "teamOvr" : 76,
      "totalLosses" : 7,
      "totalTies" : 0,
      "totalWins" : 0,
      "weekIndex" : 8,
      "winLossStreak" : 249,
      "winPct" : 0
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 4,
      "calendarYear" : 2019,
      "capAvailable" : 1150000,
      "capRoom" : 174270000,
      "capSpent" : 173120000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1785,
      "defPassYdsRank" : 16,
      "defRushYds" : 724,
      "defRushYdsRank" : 9,
      "defTotalYds" : 2509,
      "defTotalYdsRank" : 13,
      "divLosses" : 3,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761152,
      "divisionName" : "AFC East",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : 38,
      "offPassYds" : 1804,
      "offPassYdsRank" : 20,
      "offRushYds" : 1066,
      "offRushYdsRank" : 3,
      "offTotalYds" : 2870,
      "offTotalYdsRank" : 10,
      "playoffStatus" : 1,
      "prevRank" : 29,
      "ptsAgainst" : 20,
      "ptsAgainstRank" : 7,
      "ptsFor" : 25,
      "ptsForRank" : 12,
      "rank" : 10,
      "seasonIndex" : 3,
      "seed" : 4,
      "stageIndex" : 1,
      "tODiff" : 6,
      "teamId" : 757727245,
      "teamName" : "Dolphins",
      "teamOvr" : 77,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 5,
      "weekIndex" : 8,
      "winLossStreak" : 4,
      "winPct" : 0.625
    }, {
      "awayLosses" : 0,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 5630000,
      "capRoom" : 174270000,
      "capSpent" : 168640000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 2,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1762,
      "defPassYdsRank" : 14,
      "defRushYds" : 921,
      "defRushYdsRank" : 28,
      "defTotalYds" : 2683,
      "defTotalYdsRank" : 19,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761152,
      "divisionName" : "AFC East",
      "homeLosses" : 4,
      "homeTies" : 0,
      "homeWins" : 0,
      "netPts" : -26,
      "offPassYds" : 1689,
      "offPassYdsRank" : 23,
      "offRushYds" : 590,
      "offRushYdsRank" : 28,
      "offTotalYds" : 2279,
      "offTotalYdsRank" : 29,
      "playoffStatus" : 0,
      "prevRank" : 28,
      "ptsAgainst" : 24,
      "ptsAgainstRank" : 18,
      "ptsFor" : 20,
      "ptsForRank" : 26,
      "rank" : 21,
      "seasonIndex" : 3,
      "seed" : 11,
      "stageIndex" : 1,
      "tODiff" : 5,
      "teamId" : 757727252,
      "teamName" : "Jets",
      "teamOvr" : 80,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.429
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 250000,
      "capRoom" : 174270000,
      "capSpent" : 174020000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2076,
      "defPassYdsRank" : 25,
      "defRushYds" : 1002,
      "defRushYdsRank" : 30,
      "defTotalYds" : 3078,
      "defTotalYdsRank" : 30,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 4,
      "divisionId" : 755761152,
      "divisionName" : "AFC East",
      "homeLosses" : 3,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : -25,
      "offPassYds" : 2087,
      "offPassYdsRank" : 10,
      "offRushYds" : 621,
      "offRushYdsRank" : 27,
      "offTotalYds" : 2708,
      "offTotalYdsRank" : 15,
      "playoffStatus" : 0,
      "prevRank" : 2,
      "ptsAgainst" : 26,
      "ptsAgainstRank" : 24,
      "ptsFor" : 23,
      "ptsForRank" : 19,
      "rank" : 16,
      "seasonIndex" : 3,
      "seed" : 8,
      "stageIndex" : 1,
      "tODiff" : 2,
      "teamId" : 757727258,
      "teamName" : "Patriots",
      "teamOvr" : 83,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 254,
      "winPct" : 0.5
    }, {
      "awayLosses" : 3,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 2740000,
      "capRoom" : 174270000,
      "capSpent" : 171530000,
      "confLosses" : 4,
      "confTies" : 0,
      "confWins" : 1,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1587,
      "defPassYdsRank" : 1,
      "defRushYds" : 745,
      "defRushYdsRank" : 14,
      "defTotalYds" : 2332,
      "defTotalYdsRank" : 4,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761152,
      "divisionName" : "AFC East",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : -65,
      "offPassYds" : 1398,
      "offPassYdsRank" : 30,
      "offRushYds" : 819,
      "offRushYdsRank" : 13,
      "offTotalYds" : 2217,
      "offTotalYdsRank" : 30,
      "playoffStatus" : 0,
      "prevRank" : 7,
      "ptsAgainst" : 25,
      "ptsAgainstRank" : 19,
      "ptsFor" : 15,
      "ptsForRank" : 32,
      "rank" : 27,
      "seasonIndex" : 3,
      "seed" : 13,
      "stageIndex" : 1,
      "tODiff" : -9,
      "teamId" : 757727236,
      "teamName" : "Bills",
      "teamOvr" : 82,
      "totalLosses" : 5,
      "totalTies" : 0,
      "totalWins" : 2,
      "weekIndex" : 8,
      "winLossStreak" : 255,
      "winPct" : 0.286
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 3700000,
      "capRoom" : 174270000,
      "capSpent" : 170570000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1804,
      "defPassYdsRank" : 17,
      "defRushYds" : 741,
      "defRushYdsRank" : 13,
      "defTotalYds" : 2545,
      "defTotalYdsRank" : 16,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761155,
      "divisionName" : "AFC West",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -14,
      "offPassYds" : 1472,
      "offPassYdsRank" : 28,
      "offRushYds" : 840,
      "offRushYdsRank" : 12,
      "offTotalYds" : 2312,
      "offTotalYdsRank" : 27,
      "playoffStatus" : 0,
      "prevRank" : 8,
      "ptsAgainst" : 25,
      "ptsAgainstRank" : 22,
      "ptsFor" : 23,
      "ptsForRank" : 20,
      "rank" : 15,
      "seasonIndex" : 3,
      "seed" : 7,
      "stageIndex" : 1,
      "tODiff" : 6,
      "teamId" : 757727259,
      "teamName" : "Raiders",
      "teamOvr" : 82,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 2,
      "winPct" : 0.571
    }, {
      "awayLosses" : 3,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 510000,
      "capRoom" : 174270000,
      "capSpent" : 173760000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1600,
      "defPassYdsRank" : 5,
      "defRushYds" : 767,
      "defRushYdsRank" : 15,
      "defTotalYds" : 2367,
      "defTotalYdsRank" : 6,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761155,
      "divisionName" : "AFC West",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : 16,
      "offPassYds" : 2195,
      "offPassYdsRank" : 5,
      "offRushYds" : 714,
      "offRushYdsRank" : 25,
      "offTotalYds" : 2909,
      "offTotalYdsRank" : 6,
      "playoffStatus" : 0,
      "prevRank" : 30,
      "ptsAgainst" : 23,
      "ptsAgainstRank" : 11,
      "ptsFor" : 25,
      "ptsForRank" : 13,
      "rank" : 20,
      "seasonIndex" : 3,
      "seed" : 10,
      "stageIndex" : 1,
      "tODiff" : 0,
      "teamId" : 757727237,
      "teamName" : "Broncos",
      "teamOvr" : 82,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.429
    }, {
      "awayLosses" : 0,
      "awayTies" : 0,
      "awayWins" : 4,
      "calendarYear" : 2019,
      "capAvailable" : 4294797296,
      "capRoom" : 174270000,
      "capSpent" : 174440000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 2196,
      "defPassYdsRank" : 29,
      "defRushYds" : 693,
      "defRushYdsRank" : 5,
      "defTotalYds" : 2889,
      "defTotalYdsRank" : 25,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761155,
      "divisionName" : "AFC West",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : 37,
      "offPassYds" : 2155,
      "offPassYdsRank" : 7,
      "offRushYds" : 810,
      "offRushYdsRank" : 15,
      "offTotalYds" : 2965,
      "offTotalYdsRank" : 5,
      "playoffStatus" : 1,
      "prevRank" : 25,
      "ptsAgainst" : 28,
      "ptsAgainstRank" : 27,
      "ptsFor" : 33,
      "ptsForRank" : 1,
      "rank" : 7,
      "seasonIndex" : 3,
      "seed" : 3,
      "stageIndex" : 1,
      "tODiff" : 4,
      "teamId" : 757727241,
      "teamName" : "Chargers",
      "teamOvr" : 80,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 5,
      "weekIndex" : 8,
      "winLossStreak" : 5,
      "winPct" : 0.714
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 1320000,
      "capRoom" : 174270000,
      "capSpent" : 172950000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 744882176,
      "conferenceName" : "AFC",
      "defPassYds" : 1625,
      "defPassYdsRank" : 7,
      "defRushYds" : 711,
      "defRushYdsRank" : 7,
      "defTotalYds" : 2336,
      "defTotalYdsRank" : 5,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 3,
      "divisionId" : 755761155,
      "divisionName" : "AFC West",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -5,
      "offPassYds" : 1666,
      "offPassYdsRank" : 24,
      "offRushYds" : 774,
      "offRushYdsRank" : 19,
      "offTotalYds" : 2440,
      "offTotalYdsRank" : 23,
      "playoffStatus" : 1,
      "prevRank" : 6,
      "ptsAgainst" : 19,
      "ptsAgainstRank" : 3,
      "ptsFor" : 18,
      "ptsForRank" : 30,
      "rank" : 14,
      "seasonIndex" : 3,
      "seed" : 6,
      "stageIndex" : 1,
      "tODiff" : 1,
      "teamId" : 757727242,
      "teamName" : "Chiefs",
      "teamOvr" : 83,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 255,
      "winPct" : 0.571
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 12610000,
      "capRoom" : 174270000,
      "capSpent" : 161660000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1939,
      "defPassYdsRank" : 22,
      "defRushYds" : 713,
      "defRushYdsRank" : 8,
      "defTotalYds" : 2652,
      "defTotalYdsRank" : 18,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761157,
      "divisionName" : "NFC North",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 23,
      "offPassYds" : 1939,
      "offPassYdsRank" : 13,
      "offRushYds" : 813,
      "offRushYdsRank" : 14,
      "offTotalYds" : 2752,
      "offTotalYdsRank" : 13,
      "playoffStatus" : 1,
      "prevRank" : 16,
      "ptsAgainst" : 23,
      "ptsAgainstRank" : 14,
      "ptsFor" : 26,
      "ptsForRank" : 11,
      "rank" : 8,
      "seasonIndex" : 3,
      "seed" : 3,
      "stageIndex" : 1,
      "tODiff" : 3,
      "teamId" : 757727253,
      "teamName" : "Lions",
      "teamOvr" : 82,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 5,
      "weekIndex" : 8,
      "winLossStreak" : 255,
      "winPct" : 0.714
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 0,
      "calendarYear" : 2019,
      "capAvailable" : 5570000,
      "capRoom" : 174270000,
      "capSpent" : 168700000,
      "confLosses" : 6,
      "confTies" : 0,
      "confWins" : 1,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1841,
      "defPassYdsRank" : 19,
      "defRushYds" : 870,
      "defRushYdsRank" : 26,
      "defTotalYds" : 2711,
      "defTotalYdsRank" : 20,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761157,
      "divisionName" : "NFC North",
      "homeLosses" : 4,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : -124,
      "offPassYds" : 2191,
      "offPassYdsRank" : 6,
      "offRushYds" : 398,
      "offRushYdsRank" : 32,
      "offTotalYds" : 2589,
      "offTotalYdsRank" : 19,
      "playoffStatus" : 0,
      "prevRank" : 3,
      "ptsAgainst" : 38,
      "ptsAgainstRank" : 31,
      "ptsFor" : 20,
      "ptsForRank" : 27,
      "rank" : 30,
      "seasonIndex" : 3,
      "seed" : 16,
      "stageIndex" : 1,
      "tODiff" : -9,
      "teamId" : 757727256,
      "teamName" : "Packers",
      "teamOvr" : 86,
      "totalLosses" : 6,
      "totalTies" : 0,
      "totalWins" : 1,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.143
    }, {
      "awayLosses" : 3,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 850000,
      "capRoom" : 174270000,
      "capSpent" : 173420000,
      "confLosses" : 4,
      "confTies" : 0,
      "confWins" : 2,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1597,
      "defPassYdsRank" : 3,
      "defRushYds" : 803,
      "defRushYdsRank" : 18,
      "defTotalYds" : 2400,
      "defTotalYdsRank" : 7,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761157,
      "divisionName" : "NFC North",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -19,
      "offPassYds" : 1385,
      "offPassYdsRank" : 31,
      "offRushYds" : 899,
      "offRushYdsRank" : 10,
      "offTotalYds" : 2284,
      "offTotalYdsRank" : 28,
      "playoffStatus" : 0,
      "prevRank" : 24,
      "ptsAgainst" : 24,
      "ptsAgainstRank" : 15,
      "ptsFor" : 21,
      "ptsForRank" : 24,
      "rank" : 19,
      "seasonIndex" : 3,
      "seed" : 10,
      "stageIndex" : 1,
      "tODiff" : 5,
      "teamId" : 757727268,
      "teamName" : "Vikings",
      "teamOvr" : 82,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.429
    }, {
      "awayLosses" : 2,
      "awayTies" : 1,
      "awayWins" : 0,
      "calendarYear" : 2019,
      "capAvailable" : 5350000,
      "capRoom" : 174270000,
      "capSpent" : 168920000,
      "confLosses" : 3,
      "confTies" : 1,
      "confWins" : 2,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1972,
      "defPassYdsRank" : 23,
      "defRushYds" : 784,
      "defRushYdsRank" : 17,
      "defTotalYds" : 2756,
      "defTotalYdsRank" : 23,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761157,
      "divisionName" : "NFC North",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -5,
      "offPassYds" : 1934,
      "offPassYdsRank" : 14,
      "offRushYds" : 933,
      "offRushYdsRank" : 7,
      "offTotalYds" : 2867,
      "offTotalYdsRank" : 11,
      "playoffStatus" : 0,
      "prevRank" : 18,
      "ptsAgainst" : 28,
      "ptsAgainstRank" : 29,
      "ptsFor" : 27,
      "ptsForRank" : 10,
      "rank" : 25,
      "seasonIndex" : 3,
      "seed" : 13,
      "stageIndex" : 1,
      "tODiff" : 1,
      "teamId" : 757727234,
      "teamName" : "Bears",
      "teamOvr" : 80,
      "totalLosses" : 4,
      "totalTies" : 1,
      "totalWins" : 2,
      "weekIndex" : 8,
      "winLossStreak" : 254,
      "winPct" : 0.357
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 6540000,
      "capRoom" : 174270000,
      "capSpent" : 167730000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1656,
      "defPassYdsRank" : 10,
      "defRushYds" : 828,
      "defRushYdsRank" : 22,
      "defTotalYds" : 2484,
      "defTotalYdsRank" : 12,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761158,
      "divisionName" : "NFC South",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 8,
      "offPassYds" : 1612,
      "offPassYdsRank" : 25,
      "offRushYds" : 770,
      "offRushYdsRank" : 20,
      "offTotalYds" : 2382,
      "offTotalYdsRank" : 24,
      "playoffStatus" : 0,
      "prevRank" : 5,
      "ptsAgainst" : 23,
      "ptsAgainstRank" : 13,
      "ptsFor" : 24,
      "ptsForRank" : 16,
      "rank" : 12,
      "seasonIndex" : 3,
      "seed" : 8,
      "stageIndex" : 1,
      "tODiff" : 2,
      "teamId" : 757727247,
      "teamName" : "Falcons",
      "teamOvr" : 84,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 255,
      "winPct" : 0.571
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 4293967296,
      "capRoom" : 174270000,
      "capSpent" : 175270000,
      "confLosses" : 4,
      "confTies" : 0,
      "confWins" : 1,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1817,
      "defPassYdsRank" : 18,
      "defRushYds" : 734,
      "defRushYdsRank" : 11,
      "defTotalYds" : 2551,
      "defTotalYdsRank" : 17,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761158,
      "divisionName" : "NFC South",
      "homeLosses" : 3,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -15,
      "offPassYds" : 1554,
      "offPassYdsRank" : 27,
      "offRushYds" : 789,
      "offRushYdsRank" : 16,
      "offTotalYds" : 2343,
      "offTotalYdsRank" : 25,
      "playoffStatus" : 0,
      "prevRank" : 17,
      "ptsAgainst" : 21,
      "ptsAgainstRank" : 9,
      "ptsFor" : 19,
      "ptsForRank" : 29,
      "rank" : 23,
      "seasonIndex" : 3,
      "seed" : 11,
      "stageIndex" : 1,
      "tODiff" : 1,
      "teamId" : 757727257,
      "teamName" : "Panthers",
      "teamOvr" : 82,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 253,
      "winPct" : 0.429
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 26940000,
      "capRoom" : 174270000,
      "capSpent" : 147330000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 2,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1777,
      "defPassYdsRank" : 15,
      "defRushYds" : 739,
      "defRushYdsRank" : 12,
      "defTotalYds" : 2516,
      "defTotalYdsRank" : 15,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761158,
      "divisionName" : "NFC South",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 0,
      "netPts" : 3,
      "offPassYds" : 1975,
      "offPassYdsRank" : 12,
      "offRushYds" : 721,
      "offRushYdsRank" : 24,
      "offTotalYds" : 2696,
      "offTotalYdsRank" : 17,
      "playoffStatus" : 0,
      "prevRank" : 22,
      "ptsAgainst" : 25,
      "ptsAgainstRank" : 21,
      "ptsFor" : 25,
      "ptsForRank" : 14,
      "rank" : 24,
      "seasonIndex" : 3,
      "seed" : 12,
      "stageIndex" : 1,
      "tODiff" : 2,
      "teamId" : 757727263,
      "teamName" : "Saints",
      "teamOvr" : 82,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 255,
      "winPct" : 0.429
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 3840000,
      "capRoom" : 174270000,
      "capSpent" : 170430000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1597,
      "defPassYdsRank" : 4,
      "defRushYds" : 846,
      "defRushYdsRank" : 23,
      "defTotalYds" : 2443,
      "defTotalYdsRank" : 9,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761158,
      "divisionName" : "NFC South",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 26,
      "offPassYds" : 1575,
      "offPassYdsRank" : 26,
      "offRushYds" : 915,
      "offRushYdsRank" : 8,
      "offTotalYds" : 2490,
      "offTotalYdsRank" : 22,
      "playoffStatus" : 1,
      "prevRank" : 23,
      "ptsAgainst" : 23,
      "ptsAgainstRank" : 12,
      "ptsFor" : 27,
      "ptsForRank" : 9,
      "rank" : 11,
      "seasonIndex" : 3,
      "seed" : 4,
      "stageIndex" : 1,
      "tODiff" : 17,
      "teamId" : 757727239,
      "teamName" : "Buccaneers",
      "teamOvr" : 83,
      "totalLosses" : 3,
      "totalTies" : 0,
      "totalWins" : 4,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.571
    }, {
      "awayLosses" : 0,
      "awayTies" : 0,
      "awayWins" : 4,
      "calendarYear" : 2019,
      "capAvailable" : 1870000,
      "capRoom" : 174270000,
      "capSpent" : 172400000,
      "confLosses" : 1,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1737,
      "defPassYdsRank" : 13,
      "defRushYds" : 776,
      "defRushYdsRank" : 16,
      "defTotalYds" : 2513,
      "defTotalYdsRank" : 14,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761156,
      "divisionName" : "NFC East",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 110,
      "offPassYds" : 1908,
      "offPassYdsRank" : 15,
      "offRushYds" : 996,
      "offRushYdsRank" : 5,
      "offTotalYds" : 2904,
      "offTotalYdsRank" : 7,
      "playoffStatus" : 1,
      "prevRank" : 21,
      "ptsAgainst" : 18,
      "ptsAgainstRank" : 2,
      "ptsFor" : 31,
      "ptsForRank" : 6,
      "rank" : 6,
      "seasonIndex" : 3,
      "seed" : 6,
      "stageIndex" : 1,
      "tODiff" : 10,
      "teamId" : 757727244,
      "teamName" : "Cowboys",
      "teamOvr" : 84,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 1,
      "winPct" : 0.75
    }, {
      "awayLosses" : 3,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 3890000,
      "capRoom" : 174270000,
      "capSpent" : 170380000,
      "confLosses" : 3,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1885,
      "defPassYdsRank" : 20,
      "defRushYds" : 861,
      "defRushYdsRank" : 25,
      "defTotalYds" : 2746,
      "defTotalYdsRank" : 22,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 0,
      "divisionId" : 755761156,
      "divisionName" : "NFC East",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : -56,
      "offPassYds" : 1157,
      "offPassYdsRank" : 32,
      "offRushYds" : 782,
      "offRushYdsRank" : 18,
      "offTotalYds" : 1939,
      "offTotalYdsRank" : 32,
      "playoffStatus" : 0,
      "prevRank" : 12,
      "ptsAgainst" : 27,
      "ptsAgainstRank" : 26,
      "ptsFor" : 19,
      "ptsForRank" : 28,
      "rank" : 18,
      "seasonIndex" : 3,
      "seed" : 9,
      "stageIndex" : 1,
      "tODiff" : 15,
      "teamId" : 757727246,
      "teamName" : "Eagles",
      "teamOvr" : 79,
      "totalLosses" : 4,
      "totalTies" : 0,
      "totalWins" : 3,
      "weekIndex" : 8,
      "winLossStreak" : 252,
      "winPct" : 0.429
    }, {
      "awayLosses" : 2,
      "awayTies" : 0,
      "awayWins" : 2,
      "calendarYear" : 2019,
      "capAvailable" : 7510000,
      "capRoom" : 174270000,
      "capSpent" : 166760000,
      "confLosses" : 4,
      "confTies" : 1,
      "confWins" : 2,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 2142,
      "defPassYdsRank" : 27,
      "defRushYds" : 861,
      "defRushYdsRank" : 24,
      "defTotalYds" : 3003,
      "defTotalYdsRank" : 27,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761156,
      "divisionName" : "NFC East",
      "homeLosses" : 3,
      "homeTies" : 1,
      "homeWins" : 0,
      "netPts" : -38,
      "offPassYds" : 2027,
      "offPassYdsRank" : 11,
      "offRushYds" : 853,
      "offRushYdsRank" : 11,
      "offTotalYds" : 2880,
      "offTotalYdsRank" : 9,
      "playoffStatus" : 0,
      "prevRank" : 26,
      "ptsAgainst" : 25,
      "ptsAgainstRank" : 20,
      "ptsFor" : 20,
      "ptsForRank" : 25,
      "rank" : 26,
      "seasonIndex" : 3,
      "seed" : 14,
      "stageIndex" : 1,
      "tODiff" : -9,
      "teamId" : 757727249,
      "teamName" : "Giants",
      "teamOvr" : 79,
      "totalLosses" : 5,
      "totalTies" : 1,
      "totalWins" : 2,
      "weekIndex" : 8,
      "winLossStreak" : 254,
      "winPct" : 0.313
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 1660000,
      "capRoom" : 174270000,
      "capSpent" : 172610000,
      "confLosses" : 1,
      "confTies" : 0,
      "confWins" : 6,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1713,
      "defPassYdsRank" : 11,
      "defRushYds" : 726,
      "defRushYdsRank" : 10,
      "defTotalYds" : 2439,
      "defTotalYdsRank" : 8,
      "divLosses" : 0,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761156,
      "divisionName" : "NFC East",
      "homeLosses" : 0,
      "homeTies" : 0,
      "homeWins" : 3,
      "netPts" : 83,
      "offPassYds" : 1821,
      "offPassYdsRank" : 18,
      "offRushYds" : 908,
      "offRushYdsRank" : 9,
      "offTotalYds" : 2729,
      "offTotalYdsRank" : 14,
      "playoffStatus" : 1,
      "prevRank" : 31,
      "ptsAgainst" : 19,
      "ptsAgainstRank" : 5,
      "ptsFor" : 31,
      "ptsForRank" : 2,
      "rank" : 1,
      "seasonIndex" : 3,
      "seed" : 1,
      "stageIndex" : 1,
      "tODiff" : 4,
      "teamId" : 757727262,
      "teamName" : "Redskins",
      "teamOvr" : 80,
      "totalLosses" : 1,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 5,
      "winPct" : 0.857
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 3,
      "calendarYear" : 2019,
      "capAvailable" : 19510000,
      "capRoom" : 174270000,
      "capSpent" : 154760000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 4,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1735,
      "defPassYdsRank" : 12,
      "defRushYds" : 592,
      "defRushYdsRank" : 1,
      "defTotalYds" : 2327,
      "defTotalYdsRank" : 3,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761159,
      "divisionName" : "NFC West",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 3,
      "netPts" : 100,
      "offPassYds" : 2334,
      "offPassYdsRank" : 2,
      "offRushYds" : 712,
      "offRushYdsRank" : 26,
      "offTotalYds" : 3046,
      "offTotalYdsRank" : 4,
      "playoffStatus" : 1,
      "prevRank" : 1,
      "ptsAgainst" : 19,
      "ptsAgainstRank" : 4,
      "ptsFor" : 31,
      "ptsForRank" : 5,
      "rank" : 4,
      "seasonIndex" : 3,
      "seed" : 2,
      "stageIndex" : 1,
      "tODiff" : 1,
      "teamId" : 757727232,
      "teamName" : "49ers",
      "teamOvr" : 89,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 2,
      "winPct" : 0.75
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 3910000,
      "capRoom" : 174270000,
      "capSpent" : 170360000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 3,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1605,
      "defPassYdsRank" : 6,
      "defRushYds" : 703,
      "defRushYdsRank" : 6,
      "defTotalYds" : 2308,
      "defTotalYdsRank" : 2,
      "divLosses" : 1,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761159,
      "divisionName" : "NFC West",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 4,
      "netPts" : 66,
      "offPassYds" : 2197,
      "offPassYdsRank" : 4,
      "offRushYds" : 419,
      "offRushYdsRank" : 31,
      "offTotalYds" : 2616,
      "offTotalYdsRank" : 18,
      "playoffStatus" : 0,
      "prevRank" : 13,
      "ptsAgainst" : 21,
      "ptsAgainstRank" : 10,
      "ptsFor" : 31,
      "ptsForRank" : 3,
      "rank" : 9,
      "seasonIndex" : 3,
      "seed" : 7,
      "stageIndex" : 1,
      "tODiff" : 1,
      "teamId" : 757727260,
      "teamName" : "Rams",
      "teamOvr" : 81,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 5,
      "weekIndex" : 8,
      "winLossStreak" : 3,
      "winPct" : 0.714
    }, {
      "awayLosses" : 1,
      "awayTies" : 0,
      "awayWins" : 4,
      "calendarYear" : 2019,
      "capAvailable" : 450000,
      "capRoom" : 174270000,
      "capSpent" : 173820000,
      "confLosses" : 2,
      "confTies" : 0,
      "confWins" : 5,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 1642,
      "defPassYdsRank" : 8,
      "defRushYds" : 812,
      "defRushYdsRank" : 20,
      "defTotalYds" : 2454,
      "defTotalYdsRank" : 10,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 1,
      "divisionId" : 755761159,
      "divisionName" : "NFC West",
      "homeLosses" : 1,
      "homeTies" : 0,
      "homeWins" : 2,
      "netPts" : 36,
      "offPassYds" : 2233,
      "offPassYdsRank" : 3,
      "offRushYds" : 951,
      "offRushYdsRank" : 6,
      "offTotalYds" : 3184,
      "offTotalYdsRank" : 2,
      "playoffStatus" : 1,
      "prevRank" : 19,
      "ptsAgainst" : 20,
      "ptsAgainstRank" : 8,
      "ptsFor" : 25,
      "ptsForRank" : 15,
      "rank" : 5,
      "seasonIndex" : 3,
      "seed" : 5,
      "stageIndex" : 1,
      "tODiff" : -6,
      "teamId" : 757727264,
      "teamName" : "Seahawks",
      "teamOvr" : 85,
      "totalLosses" : 2,
      "totalTies" : 0,
      "totalWins" : 6,
      "weekIndex" : 8,
      "winLossStreak" : 3,
      "winPct" : 0.75
    }, {
      "awayLosses" : 4,
      "awayTies" : 0,
      "awayWins" : 1,
      "calendarYear" : 2019,
      "capAvailable" : 1000000,
      "capRoom" : 174270000,
      "capSpent" : 173270000,
      "confLosses" : 5,
      "confTies" : 0,
      "confWins" : 2,
      "conferenceId" : 747634688,
      "conferenceName" : "NFC",
      "defPassYds" : 2234,
      "defPassYdsRank" : 31,
      "defRushYds" : 1005,
      "defRushYdsRank" : 31,
      "defTotalYds" : 3239,
      "defTotalYdsRank" : 31,
      "divLosses" : 2,
      "divTies" : 0,
      "divWins" : 2,
      "divisionId" : 755761159,
      "divisionName" : "NFC West",
      "homeLosses" : 2,
      "homeTies" : 0,
      "homeWins" : 1,
      "netPts" : -43,
      "offPassYds" : 2110,
      "offPassYdsRank" : 9,
      "offRushYds" : 590,
      "offRushYdsRank" : 29,
      "offTotalYds" : 2700,
      "offTotalYdsRank" : 16,
      "playoffStatus" : 0,
      "prevRank" : 20,
      "ptsAgainst" : 26,
      "ptsAgainstRank" : 23,
      "ptsFor" : 21,
      "ptsForRank" : 23,
      "rank" : 29,
      "seasonIndex" : 3,
      "seed" : 15,
      "stageIndex" : 1,
      "tODiff" : 10,
      "teamId" : 757727240,
      "teamName" : "Cardinals",
      "teamOvr" : 80,
      "totalLosses" : 6,
      "totalTies" : 0,
      "totalWins" : 2,
      "weekIndex" : 8,
      "winLossStreak" : 253,
      "winPct" : 0.25
    } ]
    return { teams } ;
  },
  render: function() {
    return (
      <div>
        <h1>Standings</h1>
        <div className="row">
          <div className="columns small-12 medium-6">
            <h2>AFC</h2>
            <h3>East</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'AFC East') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>North</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'AFC North') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>South</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'AFC South') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>West</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'AFC West') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
          </div>
          <div className="columns small-12 medium-6">
            <h2>NFC</h2>
            <h3>East</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'NFC East') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>North</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'NFC North') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>South</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'NFC South') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
            <h3>West</h3>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Points For</th>
                    <th>Points Against</th>
                  </tr>
                </thead>
                <tbody>
                  {this.state.teams.map(function(team, i){
                    if (team.divisionName === 'NFC West') {
                      return (
                         <tr>
                           <td>{team.teamName}</td>
                           <td>{team.totalWins}</td>
                           <td>{team.totalLosses}</td>
                           <td>{team.totalTies}</td>
                           <td>{team.ptsFor}</td>
                           <td>{team.ptsAgainst}</td>
                         </tr>
                      )
                    }
                  })}
                </tbody>
              </table>
          </div>
        </div>
        <p>To do:</p>
        <ul>
          <li>Break individual tables into their own divisionalStandings component</li>
        </ul>
      </div>
    );
  }
})

module.exports = Standings;
